### ISSUE TITLE
"Query" Errors

### ISSUE THREAD

**Issue by rickycoolige** [utiso/dorkbot#2]
robot:~/dorkbot# ./dorkbot.py -i google -o engine=0099604576279661038117:vquegqft89g,query=filetype:php -s arachni
Traceback (most recent call last):
  File "./dorkbot.py", line 177, in <module>
    main()
  File "./dorkbot.py", line 69, in main
    index(db, args.indexer, args.indexer_options)
  File "./dorkbot.py", line 129, in index
    results = indexer_module.run(options)
  File "/root/dorkbot/indexers/google.py", line 46, in run
    return results
UnboundLocalError: local variable 'results' referenced before assignment
robot:~/dorkbot# 
Hello I am getting the above error... How can I resolve :(

**Comment by jgor** [comment]
Interesting! I get that error when running it with your engine id, but not with any of mine. Are you doing anything unique with your CSE that I could try re-creating?

**Comment by rickycoolige** [comment]
No.


Just running it normally, Thats the way I got it from google cse.....


----- Quote from jgor (notifications@github.com), on 15.03.2018 20:51 -----
 


Interesting! I get that error when running it with your engine id, but not
with any of mine. Are you doing anything unique with your CSE that I could
try re-creating? 


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [1], or mute the thread
[2].   
	*      




Links:
------
[1] https://github.com/utiso/dorkbot/issues/2#issuecomment-373568761
[2]

**Comment by jgor** [comment]
I notice all the examples I can find of id's are in the format: [21 numeric characters]:[11 alphanumeric], but yours is 22 characters on the left side. It also doesn't load at https://cse.google.com/cse/publicurl?cx=0099604576279661038117:vquegqft89g, but that could just be because it's private. Can you double-check that your id is correct? If so, maybe switch it to public if possible to help me troubleshoot it?

**Comment by rickycoolige** [comment]
here is the correct cse
https://cse.google.com/cse/publicurl?cx=009604576279661038117:vquegqft89g


----- Quote from jgor (notifications@github.com), on 15.03.2018 21:03 -----
 


I notice all the examples I can find of id's are in the format: [21 numeric
characters]:[11 alphanumeric], but yours is 22 characters on the left side.
It also doesn't load at
https://cse.google.com/cse/publicurl?cx=0099604576279661038117:vquegqft89g
[1], but that could just be because it's private. Can you double-check that
your id is correct? If so, maybe switch it to public if possible to help me
troubleshoot it? 


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [2], or mute the thread
[3].   
	*      




Links:
------
[1]
https://cse.google.com/cse/publicurl?cx=0099604576279661038117:vquegqft89g
[2] https://github.com/utiso/dorkbot/issues/2#issuecomment-373570654
[3]

**Comment by jgor** [comment]
Looks like it works for me with the correct cse. Work for you?

**Comment by rickycoolige** [comment]
NO... Thats why I am puzzeled, Do I need to make any changes to the script?
I did not make any changes to dorkbot.py. Do I need to ?


Do I need to make any change anywhere..... THX for all your help..


----- Quote from jgor (notifications@github.com), on 15.03.2018 21:35 -----
 


Looks like it works for me with the correct cse. Work for you? 


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [1], or mute the thread
[2].   
	*      




Links:
------
[1] https://github.com/utiso/dorkbot/issues/2#issuecomment-373575815
[2]

**Comment by jgor** [comment]
Well it works correctly for me with the new cx value you have provided, so I'm going to need more information about your environment in order to troubleshoot this further.

Also the results from this CSE appear to be public websites from across the internet. Unless you have permission from all of these website owners, it is likely ILLEGAL to run some or all of these exploits against these websites. Please do not perform these attacks against websites you do not have explicit permission to test.
